services:
  mysql:
    image: mysql:lts
    ports:
      - "3316:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # env_file:
    #   - ./.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - traefik_network
    deploy:
      restart_policy: 
        condition: any
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=dtc@sportingscout.org
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
    ports:
      - mode: host
        protocol: tcp
        target: 443
        published: 443
      - mode: host
        target: 80
        published: 80
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_network
    deploy:
      restart_policy: 
        condition: any

  api:
    image: ghcr.io/ahmed-881994/SSGG-BE-V2:staging-${GIT_COMMIT_HASH}
    ports:
      - "8001:8000"
    environment:
      - environment=stg
      - db_host=${db_host}
      - db_port=${db_port}
      - db_database=${db_database}
      - db_username=${db_username}
      - db_password=${db_password}
      - db_max_connections=${db_max_connections}
      - db_min_connections=${db_min_connections}
      - rds_host=${rds_host}
      - rds_port=${rds_port}
      - rds_database=${rds_database}
      - secret_key=${secret_key}
      - algorithm=${algorithm}
      - access_token_expire_minutes=${access_token_expire_minutes}
      - cors_origins=${cors_origins}
      - rate_limit_per_minute=${rate_limit_per_minute}
      - log_level=${log_level}
      - log_format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
    # env_file:
    #   - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.port=8000"
      - "traefik.http.routers.web.rule=Host(`api.sportingscout.org`) && PathPrefix(`/stg`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.services.web.tls.createresolver=letsencrypt"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
    networks:
      - traefik_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10
    networks:
      - traefik_network
    deploy:
      restart_policy: 
        condition: on-failure

volumes:
  redis_data_dev:
  mysql_data_dev:

networks:
  traefik_network:
    driver: overlay