services:
#------ mysql ------
  mysql:
    image: mysql:lts
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - traefik-public
    deploy:
      restart_policy: 
        condition: any
#------ traefik ------
  traefik:
    image: traefik:v3.1
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=dtc@sportingscout.org
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      -  traefik-public-certificates:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public
    deploy:
      restart_policy: 
        condition: any
#------ api ------
  api:
    image: ghcr.io/ahmed-881994/ssgg-be-v2:staging-${GIT_COMMIT_HASH}
    ports:
      - "8001:8000"
    environment:
      - environment=stg
      - db_host=${db_host}
      - db_port=${db_port}
      - db_database=${db_database}
      - db_username=${db_username}
      - db_password=${db_password}
      - db_max_connections=${db_max_connections}
      - db_min_connections=${db_min_connections}
      - rds_host=${rds_host}
      - rds_port=${rds_port}
      - rds_database=${rds_database}
      - secret_key=${secret_key}
      - algorithm=${algorithm}
      - access_token_expire_minutes=${access_token_expire_minutes}
      - cors_origins=${cors_origins}
      - rate_limit_per_minute=${rate_limit_per_minute}
      - log_level=${log_level}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api-https.loadbalancer.port=8000"
      - "traefik.http.routers.api-http.entrypoints=web"
      - "traefik.http.routers.api-http.rule=Host(`api.sportingscout.org`) && PathPrefix(`/stg`)"
      - "traefik.http.routers.api-http.middlewares=redirect-to-https"
      - "traefik.http.routers.api-https.entrypoints=websecure"
      - "traefik.http.routers.api-https.rule=Host(`api.sportingscout.org`) && PathPrefix(`/stg`)"
      - "traefik.http.routers.api-https.tls=true"
      - "traefik.http.routers.api-https.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
    networks:
      - traefik-public
#------ redis ------
  redis:
    image: redis:7
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10
    networks:
      - traefik-public
    deploy:
      restart_policy: 
        condition: on-failure

volumes:
  redis_data:
  mysql_data:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true