apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        # Link request_id from logs to related logs
        - datasourceUid: loki
          matcherRegex: '"request_id":"([^"]+)"'
          name: RequestID
          url: '$${__value.raw}'
    editable: true
