import datetime
from typing import List, Optional 
from pydantic import BaseModel, Field


class Name(BaseModel):
    en: Optional[str] = Field(alias='EN', default=None)
    ar: Optional[str] = Field(alias='AR', default=None)


class Team(BaseModel):
    team_id: Optional[int] = Field(alias='TeamID', default=None)
    is_team_leader: Optional[bool] = Field(alias='IsTeamLeader', default=None)
    date_joined: Optional[datetime.date] = Field(alias='DateJoined', default=None)
    date_transferred: Optional[datetime.date] = Field(alias='DateTransferred', default=None)
    is_current_team: Optional[bool] = Field(alias='IsCurrentTeam', default=None)
    team_name: Optional[Name] = Field(alias='TeamName', default=None)


class MemberGet(BaseModel):
    member_id: Optional[str] = Field(alias='MemberID', default=None)
    name: Optional[Name] = Field(alias='Name', default=None)
    teams: Optional[List[Team]]= Field(alias='Teams', default=None)
    place_of_birth: Optional[str] = Field(alias='PlaceOfBirth', default=None)
    date_of_birth: Optional[datetime.date] = Field(alias='DateOfBirth', default=None)
    address: Optional[str] = Field(alias='Address', default=None)
    national_id_no: Optional[str] = Field(alias='NationalIdNo', default=None)
    club_id_no: Optional[str] = Field(alias='ClubIdNo', default=None)
    passport_no: Optional[str] = Field(alias='PassportNo', default=None)
    date_joined: Optional[str] = Field(alias='DateJoined', pattern= r'^20\d{2}$', default=None)
    mobile_no: Optional[str] = Field(alias='MobileNo', default=None)
    home_contact: Optional[str] = Field(alias='HomeContact', default=None)
    email: Optional[str] = Field(alias='Email', default=None)
    facebook_url: Optional[str] = Field(alias='FacebookURL', default=None)
    school_name: Optional[str] = Field(alias='SchoolName', default=None)
    education_type: Optional[str] = Field(alias='EducationType', default=None)
    father_name: Optional[str] = Field(alias='FatherName', default=None)
    father_contact: Optional[str] = Field(alias='FatherContact', default=None)
    father_job: Optional[str] = Field(alias='FatherJob', default=None)
    mother_name: Optional[str] = Field(alias='MotherName', default=None)
    mother_contact: Optional[str] = Field(alias='MotherContact', default=None)
    mother_job: Optional[str] = Field(alias='MotherJob', default=None)
    guardian_name: Optional[str] = Field(alias='GuardianName', default=None)
    guardian_contact: Optional[str] = Field(alias='GuardianContact', default=None)
    guardian_relationship: Optional[str] = Field(alias='GuardianRelationship', default=None)
    hobbies: Optional[str] = Field(alias='Hobbies', default=None)
    health_issues: Optional[str] = Field(alias='HealthIssues', default=None)
    medications: Optional[str] = Field(alias='Medications', default=None)
    qr_code_url: Optional[str] = Field(alias='QRCodeURL', default=None)
    image_url: Optional[str] = Field(alias='ImageURL', default=None)
    national_id_url: Optional[str] = Field(alias='NationalIdURL', default=None)
    parent_national_id_url: Optional[str] = Field(alias='ParentNationalIdURL', default=None)
    club_id_url: Optional[str] = Field(alias='ClubIdURL', default=None)
    passport_url: Optional[str] = Field(alias='PassportURL', default=None)
    birth_certificate_url: Optional[str] = Field(alias='BirthCertificateURL', default=None)
    photo_consent: Optional[bool] = Field(alias='PhotoConsent', default=None)
    conditions_consent: Optional[bool] = Field(alias='ConditionsConsent', default=None)
    
  
class MemberAddUpdate(BaseModel):
    member_id: Optional[str] = Field(alias='MemberID', default=None)
    name: Optional[Name] = Field(alias='Name', default=None)
    place_of_birth: Optional[str] = Field(alias='PlaceOfBirth', default=None)
    date_of_birth: Optional[datetime.date] = Field(alias='DateOfBirth', default=None)
    address: Optional[str] = Field(alias='Address', default=None)
    national_id_no: Optional[str] = Field(alias='NationalIdNo', default=None)
    club_id_no: Optional[str] = Field(alias='ClubIdNo', default=None)
    passport_no: Optional[str] = Field(alias='PassportNo', default=None)
    date_joined: Optional[str] = Field(alias='DateJoined', pattern= r'^20\d{2}$', default=None)
    mobile_no: Optional[str] = Field(alias='MobileNo', default=None)
    home_contact: Optional[str] = Field(alias='HomeContact', default=None)
    email: Optional[str] = Field(alias='Email', default=None)
    facebook_url: Optional[str] = Field(alias='FacebookURL', default=None)
    school_name: Optional[str] = Field(alias='SchoolName', default=None)
    education_type: Optional[str] = Field(alias='EducationType', default=None)
    father_name: Optional[str] = Field(alias='FatherName', default=None)
    father_contact: Optional[str] = Field(alias='FatherContact', default=None)
    father_job: Optional[str] = Field(alias='FatherJob', default=None)
    mother_name: Optional[str] = Field(alias='MotherName', default=None)
    mother_contact: Optional[str] = Field(alias='MotherContact', default=None)
    mother_job: Optional[str] = Field(alias='MotherJob', default=None)
    guardian_name: Optional[str] = Field(alias='GuardianName', default=None)
    guardian_contact: Optional[str] = Field(alias='GuardianContact', default=None)
    guardian_relationship: Optional[str] = Field(alias='GuardianRelationship', default=None)
    hobbies: Optional[str] = Field(alias='Hobbies', default=None)
    health_issues: Optional[str] = Field(alias='HealthIssues', default=None)
    medications: Optional[str] = Field(alias='Medications', default=None)
    qr_code_url: Optional[str] = Field(alias='QRCodeURL', default=None)
    image_url: Optional[str] = Field(alias='ImageURL', default=None)
    national_id_url: Optional[str] = Field(alias='NationalIdURL', default=None)
    parent_national_id_url: Optional[str] = Field(alias='ParentNationalIdURL', default=None)
    club_id_url: Optional[str] = Field(alias='ClubIdURL', default=None)
    passport_url: Optional[str] = Field(alias='PassportURL', default=None)
    birth_certificate_url: Optional[str] = Field(alias='BirthCertificateURL', default=None)
    photo_consent: Optional[bool] = Field(alias='PhotoConsent', default=None)
    conditions_consent: Optional[bool] = Field(alias='ConditionsConsent', default=None)

class MemberAttendance(BaseModel):
    event_id: int = Field(alias='EventID')
    event_name: Name = Field(alias='EventName')
    event_start_date: datetime.date = Field(alias='EventStartDate')
    event_end_date: datetime.date = Field(alias='EventEndDate')
    event_type_name: Name = Field(alias='EventTypeName')
    attendance_state_name: Name = Field(alias='AttendanceStateName')